@ECHO OFF
cls
ECHO ....................................................................
ECHO Upgrade version according to your project-configuration file
ECHO Usage : 0_fullupdgrade username password version load-ws
ECHO Example : 0_fullupdgrade pmenacho password 5.13 true
ECHO Prerequisites : Launch script in a NEW folder (your current projects could be overwritten)
ECHO Steps :
ECHO		1 - load workspace (if load-ws defined : true or false)
ECHO		2 - accept modification
ECHO		3 - upgrade version ( before executing script : modify your project-configuration_bp.xml file and projects.txt) : POM will be upgraded
ECHO		4 - check-in ( checkin comment will be : Automated checkin : upgrade version %version)
ECHO		5 - deliver
ECHO		6 - generatedoc ( generate HTML documentation with all version)
ECHO ....................................................................

ECHO ....................................................................
ECHO 1 - LOAD WORKSPACE...
ECHO ....................................................................


IF %4==true call 1_load-ws %1 %2

ECHO ....................................................................
ECHO 2 - ACCEPT MODIFICATION...
ECHO ....................................................................

call 2_accept %1 %2

ECHO ....................................................................
ECHO 3 - UPGRADE VERSION %3...
ECHO ....................................................................

call 3_upgradeversion %3

ECHO ....................................................................
ECHO 4 - Check-in...
ECHO ....................................................................

call 4_checkin-ws %1 %2 %3

ECHO ....................................................................
ECHO 5 - Deliver...
ECHO ....................................................................

call 5_deliver-ws %1 %2


ECHO ....................................................................
ECHO 6 - Generate Doc...
ECHO ....................................................................

call 6_generatedoc %1 %2


